### ISSUE TITLE
Update at the end

### ISSUE THREAD

**Issue by smoi** [ileitch/rapns#178]
Hello,

have you maybe changed something in the delivery of push notifications? I noticed that now you update the status of the push notification at the end of the delivery with a huge update. What happens if I have to send a huge amount of push notifications and it fails at a certain point? I'll lost all the sent push not and I will not know which ones are sent and which not.

**Comment by jakeonfire** [comment]
For some issues there is no good way to figure out if they are sent or not. For example, I had an issue with our MySQL connection pool, so the update at the end to mark them as delivered was failing (there is something fishy going on as that is the only ActiveRecord update in the whole process that fails... but i digress).
So I added a monkey-patch and a subclass to the ActiveRecord Store to mark notifications delivered when they get enqueued (e.g. delivered = true); since delivered_at gets set after a successful delivery there is then a new state for notifications in the database where delivery was attempted but success is not known (delivered = true and delivered_at = null). This also prevented these notifications from being sent multiple times - at the cost of not ensuring their delivery - which for me at least is much preferred. Not sure if this helps you though.

```
require 'rapns/daemon/store/active_record'
Rapns.require_for_daemon

class FailsafeActiveRecordStore < Rapns::Daemon::Store::ActiveRecord
  def mark_batch_enqueued(notifications)
    ids = notifications.map(&:id)
    with_database_reconnect_and_retry do
      Rapns::Notification.where(id: ids).update_all(delivered: true)
    end
  end
end

Rapns::Daemon.store = FailsafeActiveRecordStore.new

module Rapns
  module Daemon
    class AppRunner
      def enqueue_with_delivery_flag_set(batch)
        # this is intended to prevent duplicate notifications at all costs since rapns will ignore
        # nofications where 'delivered' is true. check delivered_at for actual delivery success
        Rapns::Daemon.store.mark_batch_enqueued(batch.notifications)
        enqueue_without_delivery_flag_set(batch)
      end
      # this code is loaded twice because of the process forking. not much we can do about that.
      unless method_defined?(:enqueue_without_delivery_flag_set)
        alias_method_chain :enqueue, :delivery_flag_set
      end
    end
  end
end
```

**Comment by ileitch** [comment]
Yes, db updates are now performed in batches, this is an optimization. If a notification could not be sent, it will be marked as such, just like before, but with a single update.

You can disable this with `config.batch_storage_updates = false`
