### ISSUE TITLE
Exception due to db connection problem

### ISSUE THREAD

**Issue by simo2409** [ileitch/rapns#72]
Hello,
in rapns.log I'm having errors like: "[ERROR] ActiveRecord::ConnectionTimeoutError, could not obtain a database connection within 5 seconds (waited 5.000155766 seconds). The max pool size is currently 5; consider increasing it."

It looks that the problem is in /rapns/daemon/delivery_handler.rb:54 where there is a "save!"

Probably the solution would be to check if db connection is still present before calling "save!"

This problem is related with #69 (so all considerations about database pool still remains), the main problem is that we can't continue to slowly send notifications due this exception.
If "db connection loose" would be handled probably we could continue to (slowly) send notifications (while we find another way to solve the problem better)

Actually I'm not sure of my last phrase, I'm just guessing

**Comment by ileitch** [comment]
The issue is in fact the exact same as #69. The connection hasn't been lost, it is just unable to create one due to the pool being full.

**Comment by tpoland** [comment]
Actually, it looks like the error message may be mixing terms here, or perhaps there are two separate exceptions. There is a connect_error with MySQL because the database authentication does not complete within MySQL's `connect_timeout`. Increasing the timeout from 5 to 10 seconds should help with this `set global connect_timeout=10;`.

**Comment by ileitch** [comment]
@tpoland I don't think that will help. The ActiveRecord connection pool is on a per-thread basis. rapns worker threads are long lived and therefore never release their claim on a database connection. Increasing the timeout will not help because no threads are going to release their connection.

This does however make me think that the solution to this is to simply have workers explicitly release connections like a Rails request lifecycle does.

**Comment by tpoland** [comment]
@ileitch I was thinking that this should prevent the ActiveRecord ConnectTimeout perhaps abandoning less connections in the pool. Maybe the pool change could be combined with restarts of the RAPNS worker threads (via monit) at regular intervals so that you don't end up with too massive a pool.

**Comment by ileitch** [comment]
Please try 2.0.5.rc1
