### ISSUE TITLE
Best way to unit test generation of Notifications

### ISSUE THREAD

**Issue by erykwalder** [ileitch/rapns#97]
Hi, I have notifications being generated at several points in my app, and I want to test that they are being generated as they should.

The requirement to have an App to create pushes is throwing a wrench in this though. From what I can tell, I have to insert an app whenever the test database is reloaded, or reload the test database every time, which still requires me to put in the certificate password.

Is there a better way to go about unit testing Notification creation that I'm not thinking of?

Thanks a ton!

**Comment by ileitch** [comment]
Two options:

1) Generate a dummy certificate without a password. For testing, it doesn't need to be an Apple cert, any old cert will do. You can use the one rapns itself uses for testing, if you wish: https://github.com/ileitch/rapns/blob/master/spec/support/cert_without_password.pem

2) Stub calls to save! on the Notification so that validation is not triggered.

**Comment by erykwalder** [comment]
#1 will definitely work
